accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import delete_user, accounts_registration, activate, edit, add_favourite, favourites_list, like
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm, PasswordChangeForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html", form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html", form_class=PwdResetConfirmForm), name='pwdresetconfirm'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html", form_class=PasswordChangeForm), name='pwdchange'),
    path('edit/', edit, name='edit'),
    path('delete/', delete_user, name='delete_user'),
    path('favourites/', favourites_list, name='favourites_list'),
    path('like/', like, name='like'),
    path('fav/<int:id>/', add_favourite, name='add_favourite'),
    path('register/', accounts_registration, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
]

blog/urls.py
from django.urls import path
from .views import BlogPostViewSet, CategoryViewSet, blogPostsView, postDetailView, blogPostFormView, CategoryListView, post_search  #BlogPostView, BlogPostDetailView,

app_name = 'blog'

urlpatterns = [
    path('api/', BlogPostViewSet.as_view(
        {
            'get': 'list',
            'post': 'create',
        }
    )),
    path('api/<str:pk>', BlogPostViewSet.as_view(
        {
            'get': 'retrieve',
            'put': 'update',
            'delete': 'destroy',
        }
    )),
    path('category/api', CategoryViewSet.as_view(
        {
            'get': 'list',
            'post': 'create',
        }
    )),
    path('category/api/<str:pk>', CategoryViewSet.as_view(
        {
            'get': 'retrieve',
            'put': 'update',
            'delete': 'destroy',
        }
    )),
    # path('/', BlogPostView.as_view(),),
    # path('/<str:pk>', BlogPostDetailView.as_view(), name="post-detail"),
    path('', blogPostsView, name="posts"),

    path('search/', post_search, name="search"),

    path('<slug:post>', postDetailView, name="post"),

    path('create/', blogPostFormView, name="create"),

    path('category/<category>', CategoryListView.as_view(), name="category"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('repository.urls')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

def media_update(instance, filename):
    return f'posts/{instance.id}/{filename}'

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class BlogPost(models.Model):

    class Published(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status="published")

    status_options = (('draft', 'Draft'), ('published', 'Published'))

    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=255, unique=True, verbose_name='title')
    title_tag = models.CharField(max_length=255, verbose_name='title tag')
    slug = models.SlugField(max_length=255, null=False)
    image = models.ImageField(upload_to='posts/', blank=True)
    body = models.TextField(verbose_name='content')
    post_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=status_options, default='draft')
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    objects = models.Manager()
    publiished = Published() #custom manager

    def __str__(self):
        return self.title + ' | ' + str(self.post_date)

    def get_absolute_url(self):
        return reverse("blog:post", args=[self.slug])
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ["-post_date"]

class Comment(models.Model):

    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ["publish"]

    def __str__(self):
        return f"Comment by {self.name}"

templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400&display=swap" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    {% block title %}
    
    {% endblock %}
    
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/base/footer.html
<footer class="footer">
    <div class="container">
        <a href="#" class="footer__logo">
        <img src="../../static/images/logo.svg" alt="Home">
        </a>

        <div class="footer__social">
        <a href="#">
            <img src="../../static/images/logo.svg" alt="Linkedin">
        </a>
        <a href="#">
            <img src="../../static/images/logo.svg" alt="Github">
        </a>
        <a href="#">
            <img src="../../static/images/logo.svg" alt="Leetcode">
        </a>
        <a href="#">
            <img src="../../static/images/logo.svg" alt="Instagram">
        </a>
        <a href="#">
            <img src="../../static/images/logo.svg" alt="Twitter">
        </a>
        </div>

        <div class="footer__links col1">
        <a href="{% url 'home' %}#about">About Me</a>
        <a href="{% url 'home' %}#skill">Skills</a>
        <a href="{% url 'home' %}#projects">Projects</a>
        {% if user.is_authenticated %}
        {% else %}
            <a href="{% url 'home' %}#contact">Contact</a>
        {% endif %}
        </div>

        <div class="footer__links col2">
        <a href="{% url 'home' %}">Blog</a>
        {% if user.is_authenticated %}
            <a href="{% url 'home' %}#contact">Contact</a>
        {% else %}
            <a href="{% url 'accounts:register' %}">Register</a>
            <a href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
        <a href="">Category</a>
        </div>

        <div class="footer__cta">
        <a href="" class="button">Click me</a>
        </div>

        <div class="footer__copyright">
        &copy; Izzanzahrial. All Rights Reserved.
        </div>
    </div>
</footer>

templates/base/header.html
{% load static %}
<header class="header">
    <div class="overlay has-fade"></div>

    <nav class="header__container">
      <a class="header__logo" href="{% url 'home' %}">
        <img src="{% static 'images/logo.svg' %}" alt="Home">
      </a>

      <a id="btnHamburger" href="#" class="header__toggle hide-for-desktop">
        <span></span>
        <span></span>
        <span></span>
      </a>

      <div class="header__links hide-for-mobile">
        <a href="{% url 'home' %}" class="link">Home</a>
        <a href="{% url 'blog:posts' %}" class="link">Blog</a>
        <div class="header__dropdown">
          <a href="#" class="link" id="category-dropdown">Category</a>
          <div class="header__dropdown content" id="category-content">
          {% for category in category_list %}
            <a href="{% url 'blog:category' category.name %}">{{ category.name|title }}</a>
          {% endfor %}
          </div>
        </div>
        <a href="{% url 'home' %}#about" class="link">About</a>
        <a href="{% url 'home' %}#contact" class="link">Contact</a>
      </div>

      <div class="header__left hide-for-mobile">
        <form class="header__form" method="GET" action="{% url 'blog:search' %}">
          <input class="header__input" type="search" placeholder="Search" name="q">
        </form>

        {% if request.user.is_authenticated %}
        <li class="header__user">
          <a href="#" class="header__username button" id="dropdown">
            {{ user.username }}
          </a>
          <ul class="header__dropdown_user">
            <li><a href="{% url 'accounts:edit' %}" class="header__link">Edit Profile</a></li>
            <li><a href="{% url 'accounts:favourites_list' %}" class="header__link">Favourites</a></li>
            <li><a href="{% url 'password_change' %}" class="header__link">Change Password</a></li>
            <li><a href="{% url 'logout' %}" class="header__link">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <div class="header__user">
          <a class="header__link button" href="{% url 'accounts:register' %}">Register</a>
          <a class="header__link button" href="{% url 'login' %}">Login</a>
        </div>
        {% endif %}
      </div>
    </nav>

    <div class="header__menu has-fade">
      <a href="{% url 'home' %}">Home</a>
      <a href="{% url 'blog:posts' %}">Blog</a>
      <a href="#">Category</a>
      <a href="{% url 'home' %}#about">About</a>
      <a href="{% url 'home' %}#contact">Contact</a>
    </div>
</header>