accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import delete_user, accounts_registration, activate, edit, add_favourite, favourites_list, like
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm, PasswordChangeForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html", form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html", form_class=PwdResetConfirmForm), name='pwdresetconfirm'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html", form_class=PasswordChangeForm), name='pwdchange'),
    path('edit/', edit, name='edit'),
    path('delete/', delete_user, name='delete_user'),
    path('favourites/', favourites_list, name='favourites_list'),
    path('like/', like, name='like'),
    path('fav/<int:id>/', add_favourite, name='add_favourite'),
    path('register/', accounts_registration, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
]

blog/urls.py
from django.urls import path
from .views import BlogPostViewSet, CategoryViewSet, blogPostsView, postDetailView, blogPostFormView, CategoryListView, post_search  #BlogPostView, BlogPostDetailView,

app_name = 'blog'

urlpatterns = [
    path('api/', BlogPostViewSet.as_view(
        {
            'get': 'list',
            'post': 'create',
        }
    )),
    path('api/<str:pk>', BlogPostViewSet.as_view(
        {
            'get': 'retrieve',
            'put': 'update',
            'delete': 'destroy',
        }
    )),
    path('category/api', CategoryViewSet.as_view(
        {
            'get': 'list',
            'post': 'create',
        }
    )),
    path('category/api/<str:pk>', CategoryViewSet.as_view(
        {
            'get': 'retrieve',
            'put': 'update',
            'delete': 'destroy',
        }
    )),
    # path('/', BlogPostView.as_view(),),
    # path('/<str:pk>', BlogPostDetailView.as_view(), name="post-detail"),
    path('', blogPostsView, name="posts"),

    path('search/', post_search, name="search"),

    path('<slug:post>', postDetailView, name="post"),

    path('create/', blogPostFormView, name="create"),

    path('category/<category>', CategoryListView.as_view(), name="category"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('repository.urls')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# https://docs.djangoproject.com/en/3.1/topics/signals/
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from accounts.models import Profile
from django import forms
from django.contrib.auth import models
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields

# https://docs.djangoproject.com/en/3.0/topics/auth/default/
# https://docs.djangoproject.com/en/3.0/topics/forums/

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mb-3', 
        'placeholder': 'Username', 
        'id': 'login-username'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        'id': 'login-pwd',
        }
    ))

class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={'required': 'Email is required!'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name']

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exist")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already exist")
        return email

    def clean_password2(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError("Password doesn't match")
        return password2
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})

class PwdResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=255, widget=forms.TextInput(attrs={"class": "form-control mb-3", "placeholder": "email", "id": "form-email"}))

    def clean_email(self):
        email = self.cleaned_data['email']
        test = User.objects.filter(email=email)
        if not test:
            raise forms.ValidationError("Cannot find the email")
        return email

class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(attrs={"class": "form-control mb-3", "placeholder": "New Password", "id": "form-newpass"}))
    new_password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput(attrs={"class": "form-control mb-3", "placeholder": "New Password", "id": "form-new-pass2"}))

class UserEditForm(forms.ModelForm):
    
    first_name = forms.CharField(label="Firstname", min_length=4, max_length=50, required=False, widget=forms.TextInput(attrs={
        "class": "form-control mb-3",
        "placeholder": "Firstname",
        "id": "form-firstname",
    }))

    last_name = forms.CharField(label="Lastname", min_length=4, max_length=50, required=False, widget=forms.TextInput(attrs={
        "class": "form-control mb-3",
        "placeholder": "Lastname",
        "id": "form-lastname",
    }))

    email = forms.EmailField(max_length=255, required=False, widget=forms.TextInput(attrs={
        "class": "form-control mb-3",
        "placeholder": "Email",
        "id": "form-email",
    }))

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = False
        self.fields["last_name"].required = False

class UserProfileForm(forms.ModelForm):
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={
        "class": "form-control",
        "rows": 5,
    }))

    class Meta:
        model = Profile
        fields = ['bio']

class PwdChangeForm(PasswordChangeForm):

    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput(attrs={
        "class": "form-control mb-3", 
        "placeholder": "Old Password",
        "id": "form-oldpass",
    }))

    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(attrs={
        "class": "form-control mb-3", 
        "placeholder": "New Password",
        "id": "form-newpass",
    }))

    new_password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput(attrs={
        "class": "form-control mb-3", 
        "placeholder": "Repeat Password",
        "id": "form-newpass2",
    }))

accounts/views.py
from django.contrib.auth import login, tokens
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.http.response import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.db.models import F
from .forms import RegistrationForm, UserEditForm, UserProfileForm
from .token import account_activation_token
from .models import Profile
from blog.models import BlogPost

# Create your views here.

# https://docs.djangoproject.com/en/3.1/ref/models/expressions/#f-expressions
@login_required
def like(request):
    if request.POST.get('action') == 'post':
        result = ''
        id = int(request.POST.get('postid'))
        post = get_object_or_404(BlogPost, id=id)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            post.like_count -= 1
            result = post.like_count
            post.save()
        else:
            post.likes.add(request.user)
            post.like_count += 1
            result = post.like_count
            post.save()
    return JsonResponse({'result': result})

# with F expression
# @login_required
# def like(request):
#     if request.POST.get('action') == 'post':
#         result = ''
#         id = int(request.POST.get('postid'))
#         post = get_object_or_404(BlogPost, id=id)
#         if post.likes.filter(id=request.user.id).exists():
#             post.likes.remove(request.user)
#             post.like_count = F('like_count') - 1
#             result = post.like_count
#             post.save()
#         else:
#             post.likes.add(request.user)
#             post.like_count = F('like_count') + 1
#             result = post.like_count
#             post.save()
#     return JsonResponse({'result': result})

@login_required
def favourites_list(request):
    favourites = BlogPost.objects.filter(favourites=request.user)
    return render(request, 'accounts/favourites.html', {"favourites": favourites})

@login_required
def add_favourite(request, id):
    post = get_object_or_404(BlogPost, id=id)
    if post.favourites.filter(id=request.user.id).exists():
        post.favourites.remove(request.user)
    else:
        post.favourites.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def accounts_registration(request):
    if request.method == "POST":
        registrationForm = RegistrationForm(request.POST)
        if registrationForm.is_valid():
            user = registrationForm.save(commit=False)
            user.email = registrationForm.cleaned_data['email']
            user.set_password(registrationForm.cleaned_data['password'])
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('registration/activate_account.html', {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user)
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('Registration is successful, please activate your account through email')
    else:
        registrationForm = RegistrationForm()
    return render(request, 'registration/register.html', {'form': registrationForm})
    
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('login')
    else:
        return render(request, 'registration/activation_invalid.html')

@login_required
def edit(request):
    if request.method == "POST":
        user_edit_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_edit_form.is_valid() and profile_form.is_valid():
            user_edit_form.save()
            profile_form.save()
    else:
        user_edit_form = UserEditForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.profile)
    return render(request, 'accounts/update.html', {"form": user_edit_form, "profile_form": profile_form})

@login_required
def delete_user(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        user.is_active = False
        user.save()
        return redirect('accounts:login')
    return render(request, 'accounts/delete.html')

templates/accounts/delete.html
{% extends "../base/base.html" %}
{% block title %}
<title>Profile</title>
{% endblock %}
{% block content %}

<div class="container-fluid my-5">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <form class="form-reset p-4 rounded update-form" action="{% url "accounts:delete_user" %}" method="post">
                    {% csrf_token %}
                    <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                    <p>Are you sure you want to delete your account?
                        *Important - your account data will remain available for 20 days</p>
                    <button type="submit" role="button"
                        class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold">Delete</button>
                </form>
                <p class="small text-center pt-4">
                    <a href="{% url "blog:posts" %}">Back to Blog</a>
                </p>
                <p class="small text-center">
                    <a href="{% url "accounts:register" %}">Register</a>
                </p>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/accounts/favourites.html
{% extends '../base/base.html' %}

{% block title %}
<title>Favourites</title>
{% endblock %}

{% block content %}

{% include 'base/header.html' %}

{% load static %}

<div class="container text-center">
    <h1>User saved favourites post</h1>
</div>
<section class="album py-5 bg-light">
    <div class="container">
        <div class="row">
        {{ favourites }}
            {% for post in favourites %}
            <div class="col-md-4">
                <a href="{{ post.get_absolute_url }}" class="text-dark">
                    <div class="card mb-4 box-shadow">
                        {% if post.image.url is not None %}
                            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="card-img-top">
                        {% endif %}
                        <div class="card-body">
                            <p style="font-size:18px;font-weight:bold">{{ post.title|truncatechars:50 }}</p>
                            <p class="card-text">{{ post.title_tag }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{ post.post_date }}</small>
                                <div id="favourites-section">
                                    <a href="{% url 'accounts:add_favourite' post.id %}">
                                        <img src="{% static 'images/favourite-yes.svg' %}">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include '../base/footer.html' %}
{% endblock %}

templates/accounts/update.html
{% extends "../base/base.html" %}
{% block title %}
<title>Edit your account</title>
{% endblock %}
{% block content %}
{% include "base/header.html" %}
<style>
    .update-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .update-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid my-5">
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">

                <form class="form-reset p-4 rounded update-form" method="post" enctype="multipart/form-data">

                    {% if form.is_valid %}
                    <div class="alert alert-primary" role="alert">
                        Details successfully updated!
                    </div>
                    <p class="small text-center pt-0">
                        <a href="{% url "blog:posts" %}">Back to Blog</a>
                    </p>
                    {%else%}
                    <p class=" h4 mb-4 font-weight-bold">Change your details</p>
                    <p>You can edit your account using the following form:</p>
                    {% endif %}

                    {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                        {{ form.errors.as_text }}
                    </div>
                    {% endif %}

                    {% csrf_token %}
                    <label class="small font-weight-bold mb-2">{{ form.first_name.label }}</label>
                    {{ form.first_name }}
                    <label class="small font-weight-bold mb-2">{{ form.last_name.label }}</label>
                    {{ form.last_name }}
                    <label class="small font-weight-bold mb-2">{{ form.email.label }}</label>
                    {{ form.email }}
                    <label class="small font-weight-bold mb-2">{{ profile_form.bio.label }}</label>
                    {{ profile_form.bio }}
                    <button class="btn btn-block button py-2 mb-4 mt-5 font-weight-bold" type="submit"
                        value="Save changes">Save Changes</button>
                    <hr class="mb-3">
                    <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                    <p class="small">If you would like to delete your account press the button below:</p>
                    <a href="{% url "accounts:delete_user" %}"
                        class="btn btn-danger btn-block py-2 mb-4 mt-3 font-weight-bold" role="button"
                        aria-pressed="true">Delete Account</a>
                </form>

            </div>
        </div>
    </section>
</div>
{% include "base/footer.html" %}
{% endblock %}