accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import delete_user, accounts_registration, activate, edit, add_favourite, favourites_list, like
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm, PasswordChangeForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html", form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html", form_class=PwdResetConfirmForm), name='pwdresetconfirm'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="registration/password_change_form.html", form_class=PasswordChangeForm), name='pwdchange'),
    path('edit/', edit, name='edit'),
    path('delete/', delete_user, name='delete_user'),
    path('favourites/', favourites_list, name='favourites_list'),
    path('like/', like, name='like'),
    path('fav/<int:id>/', add_favourite, name='add_favourite'),
    path('register/', accounts_registration, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
]

blog/urls.py
from django.urls import path
from .views import BlogPostViewSet, CategoryViewSet, blogPostsView, postDetailView, blogPostFormView, CategoryListView, post_search  #BlogPostView, BlogPostDetailView,

app_name = 'blog'

urlpatterns = [
    path('api/', BlogPostViewSet.as_view(
        {
            'get': 'list',
            'post': 'create',
        }
    )),
    path('api/<str:pk>', BlogPostViewSet.as_view(
        {
            'get': 'retrieve',
            'put': 'update',
            'delete': 'destroy',
        }
    )),
    path('category/api', CategoryViewSet.as_view(
        {
            'get': 'list',
            'post': 'create',
        }
    )),
    path('category/api/<str:pk>', CategoryViewSet.as_view(
        {
            'get': 'retrieve',
            'put': 'update',
            'delete': 'destroy',
        }
    )),
    # path('/', BlogPostView.as_view(),),
    # path('/<str:pk>', BlogPostDetailView.as_view(), name="post-detail"),
    path('', blogPostsView, name="posts"),

    path('search/', post_search, name="search"),

    path('<slug:post>', postDetailView, name="post"),

    path('create/', blogPostFormView, name="create"),

    path('category/<category>', CategoryListView.as_view(), name="category"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('secret/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('repository.urls')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

def media_update(instance, filename):
    return f'posts/{instance.id}/{filename}'

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class BlogPost(models.Model):

    class Published(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status="published")

    status_options = (('draft', 'Draft'), ('published', 'Published'))

    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=255, unique=True, verbose_name='title')
    title_tag = models.CharField(max_length=255, verbose_name='title tag')
    slug = models.SlugField(max_length=255, null=False)
    image = models.ImageField(upload_to='posts/', blank=True)
    body = models.TextField(verbose_name='content')
    post_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=status_options, default='draft')
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    objects = models.Manager()
    publiished = Published() #custom manager

    def __str__(self):
        return self.title + ' | ' + str(self.post_date)

    def get_absolute_url(self):
        return reverse("blog:post", args=[self.slug])
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ["-post_date"]

class Comment(models.Model):

    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ["publish"]

    def __str__(self):
        return f"Comment by {self.name}"

blog/forms.py
from django import forms
from django.forms import fields, widgets
from .models import BlogPost, Comment

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'title_tag', 'body', 'category']
        widgets = {
            "title": forms.TextInput(attrs={"class": ""}),
            "title_tag": forms.TextInput(attrs={"class": ""}),
            "body": forms.Textarea(attrs={"class": ""}),
            "category": forms.TextInput(attrs={"class": ""}),
            "image": forms.ImageField()
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            "name": forms.TextInput(attrs={"class": "col-sm-12 mb-3"}),
            "email": forms.EmailInput(attrs={"class": "col-sm-12 mb-3"}),
            "body": forms.Textarea(attrs={"class": "form-control mb-3"}),
        }

class PostSearchForm(forms.Form):
    q = forms.CharField()

blog/views.py
import time
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import paginator
# from core.settings import URL
from django.http import request
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from rest_framework import serializers, viewsets, status
from rest_framework.response import Response
from datetime import timedelta, date
from .models import BlogPost, Category, Comment
from .serializer import BlogPostSerializer, CategorySerializer
from .forms import BlogPostForm, CommentForm, PostSearchForm
from .decorator import allowed_users

import requests

# Create your views here.
class BlogPostViewSet(LoginRequiredMixin, viewsets.ViewSet):
    login_url = "/account/login/"
    redirect_field_name = "login"

    def list(self, request):
        blogPosts = BlogPost.objects.all()
        serializer = BlogPostSerializer(blogPosts, many=True)
        return Response(serializer.data)

    def create(self, request):
        serializer = BlogPostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def retrieve(self, request, pk=None):
        blogPost = BlogPost.objects.get(id=pk)
        serializer = BlogPostSerializer(blogPost)
        return Response(serializer.data)

    def update(self, request, pk=None):
        blogPost = BlogPost.objects.get(id=pk)
        serializer = BlogPostSerializer(instance=blogPost, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_202_ACCEPTED)

    def destroy(self, request, pk=None):
        blogPost = BlogPost.objects.get(id=pk)
        blogPost.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class CategoryViewSet(LoginRequiredMixin, viewsets.ViewSet):
    login_url = "/account/login/"
    redirect_field_name = "login"
    
    def list(self, request):
        category = Category.objects.all()
        serializer = CategorySerializer(category, many=True)
        return Response(serializer.data)

    def create(self, request):
        serializer = CategorySerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def retrieve(self, request, pk=None):
        category = Category.objects.get(id=pk)
        serializer = CategorySerializer(category)
        return Response(serializer.data)

    def update(self, request, pk=None):
        category = Category.objects.get(id=pk)
        serializer = CategorySerializer(instance=category, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_202_ACCEPTED)

    def destroy(self, request, pk=None):
        category = Category.objects.get(id=pk)
        category.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class CategoryListView(ListView):
    template_name = 'blog/category.html'
    context_object_name = 'categories'

    def get_queryset(self):
        # posts = BlogPost.objects.filter(category__name= self.kwargs['category'])
        # posts_date = []

        # # turn every post date into range from post created until now
        # for post in posts:
        #     posts_date.append(post_created(post.post_date))

        content = {
            'category': self.kwargs['category'],
            'posts': BlogPost.objects.filter(category__name= self.kwargs['category']),
            # 'posts_date' : posts_date,
            #'posts': BlogPost.objects.filter(category__name= self.kwargs['category']).filter(status='published')
        }
        return content

def blogPostsView(request):

    posts = BlogPost.objects.all().order_by('-id')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    blogposts = paginator.get_page(page_number)
    #published_posts = BlogPost.publiished.all()

    return render(request, 'blog/blogpost.html', {"blogposts": blogposts})

def postDetailView(request, post=None):
    
    post = get_object_or_404(BlogPost, slug=post)
    #blogDetail = get_object_or_404(BlogPost, slug=post, status="published")

    fav = bool
    
    if post.favourites.filter(id=request.user.id).exists():
        fav = True

    comments = Comment.objects.filter(status=True)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect('/blog/' + post.slug)
    else:
        comment_form = CommentForm()
    
    return render(request, "blog/post.html", {"post": post, "comments": comments, "comment_form": comment_form, "fav":fav})

@login_required
@allowed_users(allowed_roles=['admin'])
def blogPostFormView(request):
    
    #using API
    #URL = "http://host.dokcer.internal:8000/repository/api"

    if request.method == "POST":
        blog_post_form = BlogPostForm(request.POST)

        if blog_post_form.is_valid():
            blog_post = blog_post_form.save()
            return HttpResponseRedirect('/blog/' + blog_post.slug)

        #using API
        # requests.post(url=URL, data=blog_post_form)
        # return HttpResponseRedirect('/blog/')

    else:
        blog_post_form = BlogPostForm()
    
    return render(request, 'blog/create.html', {'blog_post_form': blog_post_form})

def category_list(request):
    category_list = Category.objects.all()
    context = {
        "category_list": category_list,
    }
    return context

def post_search(request):
    form = PostSearchForm()
    q = ''
    results = []

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            results = BlogPost.objects.filter(title__contains=q)
        
    return render(request, 'blog/search.html', {'form': form, 'q':q, 'results':results})

# def post_created(post_date):
#     today = date.today()
#     days1 = (today.year * 365) + (today.month * 30) + today.day
#     days2 = (int(post_date[9:]) *365) + (int(post_date[0:3]) * 30) + int(post_date[5:7])
#     time1 = timedelta(days=days1)
#     time2 = timedelta(days=days2)
#     time = time1 - time2
#     return time.days

templates/blog/blogpost.html
{% extends '../base/base.html' %}

{% block title %}
    <title>Blog Posts</title>
{% endblock %}

{% block content %}

{% include 'base/header.html' %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {% for post in blogposts %}
            <div class="post">
                <div class="post__header">
                    <h2>
                        <a href="{{ post.get_absolute_url }}" class="title">{{ post.title }}</a>
                    </h2>
                </div>
                <div class="post__body row justify-content-start">
                    <div class="post__content col-8">
                        <div class="post__title-tag"><p>{{ post.title_tag }}</p></div>
                        <div class="post__date"><p>{{ post.post_date }}</p></div>
                        <div class="post__category"><p>{{ post.category }}</p></div>
                    </div>
                    {% if post.image.url is not None %}
                    <div class="post__image-container col-4">
                        <a href="{{ post.get_absolute_url }}">
                            <img class="post__image" src="../media/{{ post.image }}" alt="">
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="post__page">
            {% comment %} {% if is_paginated %} {% endcomment %}
                {% if blogposts.has_previous %}
                    <a href="?page=1" class="button">first</a>
                    <a href="?page={{ blogposts.previous_page_number }}" class="button">previous</a>
                {% endif %}
                {% for num in blogposts.paginator.page_range %}
                    {% if blogposts.number == num %}
                        <a href="?page={{ num }}" class="button" id="current-page">{{ num }}</a>
                    {% elif num > blogposts.number|add:'-3' and num < blogposts.number|add:'3' %}
                        <a href="?page={{ num }}" class="button">{{ num }}</a>
                    {% endif %}
                {% endfor %}
                {% if blogposts.has_next %}
                    <a href="?page={{ blogposts.next_page_number }}" class="button">next</a>
                    <a href="?page={{ blogposts.paginator.num_pages }}" class="button">last</a>
                {% endif %}
            {% comment %} {% endif %} {% endcomment %}
            </div>
        </div>
    </div>
</div>

{% include "base/footer.html" %}

{% endblock %}

templates/blog/category.html
{% extends '../base/base.html' %}

{% block title %}
    <title>Category</title>
{% endblock %}

{% block content %}

{% include 'base/header.html' %}

{% load humanize %}

<div class="categories__title container">
    <h1>List of {{ categories.category }} posts</h1>
    <p>
        {% with categories.posts.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>
</div>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in categories.posts %}
            <div class="col-md-4">
                <a href="{{ post.get_absolute_url }}" class="text-dark">
                    <div class="card mb-4 box-shadow">
                        {% if post.image.url is not None %}
                            <img src="{{ post.image.url }}" alt="Card image" class="card-img-top">
                        {% endif %}
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title|truncatechars:50 }}</h2>
                            <p class="card-text">{{ post.body|truncatechars:50|safe }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{ post.post_date|naturalday }}</small>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "base/footer.html" %}

{% endblock  %}

templates/blog/create.html
{% extends '../base/base.html' %}

{% block title %}
    <title>Create Post</title>
{% endblock %}

{% block content %}

{% include 'base/header.html' %}

<h1>Create Post</h1>

<form action="{% url 'blog:create' %}" method="POST">
    {% csrf_token %}
    {{ blog_post_form.as_p }}
    <button type="submit">Submit</button>
</form>

{% include "base/footer.html" %}

{% endblock content %}

templates/blog/post.html
{% extends '../base/base.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}

{% include 'base/header.html' %}

{% load static %}

<div class="container">
    <div class="row justify-content-md-center pt-4">
        <div class="col-md-8 d-flex justify-content-between" style="flex-direction: column">
            <h1 class="post__title">{{ post.title }}</h1>
            <div class="col-12 no-gutters smaller">{{ post.title_tag }}</div>
        </div>
        <div class="col-md-8 d-flex justify-content-between">
            <div class="post__title-tag d-flex">
                <div class="post__title-tag-1 no-gutters smaller">{{ post.category|title }}</div>
                <div class="no-gutters smaller">{{ post.post_date }}</div>
            </div>
            <div class="d-flex">
            {% if request.user.is_authenticated %}
                <div class="pr-2">
                    <span class="" id="like_count">{{ post.like_count }}</span>
                    <button class="btn btn-link text-dark p-0 border-0" id="like-button" value="{{ post.id }}">
                        <img src="{% static 'images/like-button.svg' %}" class="post__icon-like">
                    </button>
                </div>
                {% if fav %}
                <div>
                    <a href="{% url 'accounts:add_favourite' post.id %}" class="text-dark">
                        <img src="{% static 'images/favourite-yes.svg' %}" class="post__icon">
                    </a>
                </div>
                {% else %}
                <div>
                    <a href="{% url 'accounts:add_favourite' post.id %}" class="text-dark">
                        <img src="{% static 'images/favourite-no.svg' %}" class="post__icon">
                    </a>
                </div>
                {% endif %}
                {% else %}
                <div class="pr-2">
                    <span class="" id="like_count">{{ post.like_count }}</span>
                    <a href="{% url 'accounts:register' %}" class="btn btn-link text-dark p-0 border-0" value="{{ post.id }}">
                        <img src="{% static 'images/like-button.svg' %}" class="post__icon-like">
                    </a>
                </div>
                <div>
                    <a href="{% url 'accounts:register' %}" class="text-dark"> 
                        <img src="{% static 'images/favourite-no.svg' %}" class="post__icon">
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-8 pt-3">
            {% if post.image.url is not None %}
                <img class="card-img-top pb-3" src="{{ post.image.url }}" alt="{{ post.title }}">
            {% endif %}
            <p class="mb-3">{{ post.body|safe }}</p>
        </div>
        <div class="col-md-8">
        {% with comments.count as total_comments %}
            <p class="mb-1 mt-3">{{ total_comments }} comment{{ total_comments|pluralize }}</p>
        {% endwith %}
            <div>
                <div class="my-2 p-2">
            {% for comment in comments %}
                    <div class="d-flex justify-content-between mb-2 fs-6">By {{ comment.name }}<div></div>{{ comment.publish }}</div>
                    <div class="fs-6">{{ comment.body|linebreaks }}</div>
                    {% empty %}
                    <p>There are no comment for this post</p>
            {% endfor %}
                </div>
            </div>
            <h4 class="mb-3">Make a new comment</h4>
            <form id="commentForm" method="POST">
                <div class="container">{{ comment_form }}</div>
                {% csrf_token %}
                <button type="submit" class="button">Submit</button>
            </form>
        </div>
        {% comment %} <div class="col-12">
            <h2>{{ post.title_tag }}</h2>
        </div>
        {% if post.image.url is not None %}
            <div class="col-12">
                <a href="{{ post.get_absolute_url }}">
                    <img src="../media/{{ post.image }}" alt="{{ post.title }}">
                </a>
            </div>
        {% endif %}
        <div class="col-12">
            <p>{{ post.body }}</p>
        </div>
        <div class="col-12">
            <p>{{ post.post_date }}</p>
        </div>
        <div class="col-12">
            <p>{{ post.category }}</p>
        </div>
        <a href={% url 'blog:posts' %}>Back</a>
        <div class="col-md-12">
            {% with comments.count as total_comments %}
                <h2>{{ total_comments }} comment{{ total_comments|pluralize }}
            {% endwith %}
            {% for comment in comments %}
                Comment {{ forloop.counter }} by {{ comment.name }}
                on {{ comment.publish }}
                {{ comment.body|linebreaks }}
                {% empty %}
                <p>There are no comment for this post</p>
            {% endfor %}
            
            <h2>Make a new comment</h2>

            <form id="commentForm" method="POST">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
            </form>
        </div> {% endcomment %}
    </div>
</div>

{% include "base/footer.html" %}

<script>
$(document).on('click', '#like-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "accounts:like" %}',
      data: {
        postid: $('#like-button').val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        action: 'post'
      },
      success: function (json) {
        document.getElementById("like_count").innerHTML = json['result']
      },
      error: function (xhr, errmsg, err) {

      }
    });
})
</script>

{% endblock content %}

templates/blog/search.html
{% extends '../base/base.html' %}

{% block title %}
    <title>Search</title>
{% endblock %}

{% block content %}

{% include '../base/header.html' %}

<form method="GET">
    {{ form.q.as_hidden }}
</form>

{% if q %}
    <div class="search__title container">
        <h1>Posts containing "{{ q }}"</h1>
        <p>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </p>
    </div>
{% endif %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in results %}
                <div class="col-md-4">
                    <a href="{{ post.get_absolute_url }}" class="text-dark">
                        <div class="card mb-4 box-shadow">
                            {% if post.image.url is not None %}
                            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="card-img-top">
                            {% endif %}
                            <div class="card-body">
                                <h2 class="card-title">{{ post.title|truncatechars:50 }}</h2>
                                <p class="card-text">{{ post.title_tag }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{ post.post_date }}</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% empty %}
                <p>There are no result for your search
            {% endfor %}
        </div>
    </div>
</div>

{% include "base/footer.html" %}    

{% endblock %}